### ISSUE TITLE
Directory selection not possible on Linux (NixOS unstable with GNOME)

### ISSUE THREAD

**Issue by das-g** [Git-it-App/git-it-electron#688]
### To reproduce:
1. go to https://github.com/Git-it-App/git-it-electron
2. click on the latest release in the section on the right (currently [v5.2.2](https://github.com/Git-it-App/git-it-electron/releases/tag/v5.2.2) based on a50f82f87d24ae67dd21b95ac40895de2f3f2b50)
3. download `Git-it-linux-x64.zip`
4. unpack the zip archive
5. open a terminal in the directory `Git-it-linux-x64` created by that unzipping, or `cd` there in an already open terminal window
6. run
    ```bash
    NIXPKGS_ALLOW_UNFREE=1 nix run --impure nixpkgs#steam-run -- ./Git-it
    ```
7. in the Git-it app, click on the circle of the second challenge "repository"
8. scroll down to bring the blue "Please select your repository directory." box into view
9. in that box, click the button "Select directory"

#### expected

- a directory choosing dialog appears and a directory can be selected there

(This is also what happens when trying this with https://github.com/jlord/git-it-electron/releases/tag/4.4.0 instead.)

#### observed

- no directory choosing dialog appears
  - sometimes a window quickly appears and instantaneously vanishes again. Too quick (just flashing for much less than a second, maybe just a single frame) to make out what its contents would be.
- on the command line output (which until then was just
  ```
  [84093:0613/163148.713087:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
  ```
  a new line
  ```
  [84057:0613/163620.047068:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
  ```
  appears just when the button was clicked.

### Output of `nix-info -m`

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.91, NixOS, 24.11 (Vicuña), 24.11.20240524.bfb7a88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(das-g): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source`

**Comment by jotoeri** [comment]
Seems to have been a bug in electron that once. Should be fixed in the meantime (and thus with the next release here).
